version: "3"

services:
  jaeger:
    image: "jaegertracing/all-in-one:latest"
    network_mode: "host"
    ports:
      - "16686:16686"
      - "14268"
      - "14250"
      - "4317"
    environment:
      - COLLECTOR_OTLP_ENABLED=true
